updated mui deps and added not found message
unfoldingWord/findr pull request #38
Opened 2024-01-02 23:11 UTC by abelpz

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Updated MUI material dependencies to solve tree view results not showing with newer versions due to https://mui.com/blog/lab-tree-view-to-mui-x/

- Fixed playground not working because of missing theme-provider.

#### Please include detailed Test instructions for your pull request:
- Run the playground by executing the command `pnpm nx serve fnr-pg` search one of the cards, results should show if any, a "No results found" message should show if none. 

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Is the repo documentation accurate/appropriate?
  - [ ] Check Stylguidist if applicable
  - [ ] Check readme for correct information about the feature being worked on
- [ ] Check that there are not inadvertent commits 
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story

2024-01-03 20:58 UTC, kintsoogi requested changes
The update works and looks good to me!
I just left one question about an added import that seems to be unused

2024-01-03 20:58 UTC, kintsoogi commented on packages/fnr-mui/src/results-tree/results-tree.tsx
> +import { devNull } from 'os';
What is the `devNull` imported here being used for?

2024-01-03 20:58 UTC, kintsoogi commented on packages/fnr-mui/src/findr-results/findr-results.tsx
> +              ? <Alert severity="info">No results found</Alert>
The "no results found" is a great addition!

2024-01-04 00:05 UTC, abelpz commented on packages/fnr-mui/src/results-tree/results-tree.tsx
> +import { devNull } from 'os';
Some vscode extension added that automatically it must have suggested it to me and I accepted it by mistake.

2024-01-04 15:38 UTC, kintsoogi approved these changes
LGTM

2024-01-04 16:35 UTC, merged